FROM python:3.10-slim

# Set workdir
WORKDIR /app

# Install Poetry
RUN pip install poetry

# Disable Poetry virtualenvs for Docker
RUN poetry config virtualenvs.create false

# Copy and install dependencies
COPY pyproject.toml poetry.lock* ./
RUN poetry install --no-root

# Copy the source code
COPY . .


CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
